version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: tarkov_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: .
    container_name: tarkov_server
    restart: always
    depends_on:
      - mongodb
    environment:
      DB_URI: mongodb://admin:rootpassword@mongodb:27017/tarkov_db
      PORT: 3000
    ports:
      - "3000:3000"

volumes:
  mongo_data:
